---
# keep-sorted start
Bundler/GemComment:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
RSpec/AlignLeftLetBrace:
  Enabled: false
RSpec/AlignRightLetBrace:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MissingElse:
  Enabled: false
# keep-sorted end
