---
# keep-sorted start
RSpec/DescribeClass:
  Exclude:
    - 'spec/nix/pure/*/*.nixsh_spec.rb'
    - 'spec/standards/rspec/coverage_spec.rb'
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/standards/rspec/coverage_spec.rb
RSpec/NestedGroups:
  Exclude:
    - spec/standards/rspec/coverage_spec.rb
# keep-sorted end
